config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :rubric_aspects
  resources :rubrics
  resources :plan_aspects
  resources :plans
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/rubric.rb
class Rubric < ApplicationRecord
  belongs_to :rubricable, polymorphic: true, optional: true
  has_many :rubric_aspects
end

app/controllers/rubrics_controller.rb
class RubricsController < ApplicationController
  before_action :set_rubric, only: [:show, :edit, :update, :destroy]

  # GET /rubrics
  # GET /rubrics.json
  def index
    @rubrics = Rubric.all
  end

  # GET /rubrics/1
  # GET /rubrics/1.json
  def show
  end

  # GET /rubrics/new
  def new
    @rubric = Rubric.new
  end

  # GET /rubrics/1/edit
  def edit
  end

  # POST /rubrics
  # POST /rubrics.json
  def create
    @rubric = Rubric.new(rubric_params)

    respond_to do |format|
      if @rubric.save
        format.html { redirect_to @rubric, notice: 'Rubric was successfully created.' }
        format.json { render :show, status: :created, location: @rubric }
      else
        format.html { render :new }
        format.json { render json: @rubric.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rubrics/1
  # PATCH/PUT /rubrics/1.json
  def update
    respond_to do |format|
      if @rubric.update(rubric_params)
        format.html { redirect_to @rubric, notice: 'Rubric was successfully updated.' }
        format.json { render :show, status: :ok, location: @rubric }
      else
        format.html { render :edit }
        format.json { render json: @rubric.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rubrics/1
  # DELETE /rubrics/1.json
  def destroy
    @rubric.destroy
    respond_to do |format|
      format.html { redirect_to rubrics_url, notice: 'Rubric was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rubric
      @rubric = Rubric.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rubric_params
      params.require(:rubric).permit(:name)
    end
end

app/helpers/rubrics_helper.rb
module RubricsHelper
end

app/views/rubrics/_form.html.erb
<%= form_with(model: rubric, local: true) do |form| %>
  <% if rubric.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rubric.errors.count, "error") %> prohibited this rubric from being saved:</h2>

      <ul>
        <% rubric.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rubrics/edit.html.erb
<h1>Editing Rubric</h1>

<%= render 'form', rubric: @rubric %>

<%= link_to 'Show', @rubric %> |
<%= link_to 'Back', rubrics_path %>

app/views/rubrics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rubrics</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rubrics.each do |rubric| %>
      <tr>
        <td><%= rubric.name %></td>
        <td><%= link_to 'Show', rubric %></td>
        <td><%= link_to 'Edit', edit_rubric_path(rubric) %></td>
        <td><%= link_to 'Destroy', rubric, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rubric', new_rubric_path %>

app/views/rubrics/new.html.erb
<h1>New Rubric</h1>

<%= render 'form', rubric: @rubric %>

<%= link_to 'Back', rubrics_path %>

app/views/rubrics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @rubric.name %>
</p>

<%= link_to 'Edit', edit_rubric_path(@rubric) %> |
<%= link_to 'Back', rubrics_path %>