config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :rubric_aspects
  resources :rubrics
  resources :plan_aspects
  resources :plans
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/plan_aspect.rb
class PlanAspect < ApplicationRecord
  has_many :rubrics, as: :rubricable
  has_many :user_rubrics, as: :user_rubricable
  has_many :user_joins, as: :user_joinable
  has_many :users, through: :user_joins
end

app/controllers/plan_aspects_controller.rb
class PlanAspectsController < ApplicationController
  before_action :set_plan_aspect, only: [:show, :edit, :update, :destroy]

  # GET /plan_aspects
  # GET /plan_aspects.json
  def index
    @plan_aspects = PlanAspect.all
  end

  # GET /plan_aspects/1
  # GET /plan_aspects/1.json
  def show
  end

  # GET /plan_aspects/new
  def new
    @plan_aspect = PlanAspect.new
  end

  # GET /plan_aspects/1/edit
  def edit
  end

  # POST /plan_aspects
  # POST /plan_aspects.json
  def create
    @plan_aspect = PlanAspect.new(plan_aspect_params)

    respond_to do |format|
      if @plan_aspect.save
        format.html { redirect_to @plan_aspect, notice: 'Plan aspect was successfully created.' }
        format.json { render :show, status: :created, location: @plan_aspect }
      else
        format.html { render :new }
        format.json { render json: @plan_aspect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plan_aspects/1
  # PATCH/PUT /plan_aspects/1.json
  def update
    respond_to do |format|
      if @plan_aspect.update(plan_aspect_params)
        format.html { redirect_to @plan_aspect, notice: 'Plan aspect was successfully updated.' }
        format.json { render :show, status: :ok, location: @plan_aspect }
      else
        format.html { render :edit }
        format.json { render json: @plan_aspect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plan_aspects/1
  # DELETE /plan_aspects/1.json
  def destroy
    @plan_aspect.destroy
    respond_to do |format|
      format.html { redirect_to plan_aspects_url, notice: 'Plan aspect was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan_aspect
      @plan_aspect = PlanAspect.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def plan_aspect_params
      params.require(:plan_aspect).permit(:name)
    end
end

app/helpers/plan_aspects_helper.rb
module PlanAspectsHelper
end

app/views/plan_aspects/_form.html.erb
<%= form_with(model: plan_aspect, local: true) do |form| %>
  <% if plan_aspect.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plan_aspect.errors.count, "error") %> prohibited this plan_aspect from being saved:</h2>

      <ul>
        <% plan_aspect.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/plan_aspects/edit.html.erb
<h1>Editing Plan Aspect</h1>

<%= render 'form', plan_aspect: @plan_aspect %>

<%= link_to 'Show', @plan_aspect %> |
<%= link_to 'Back', plan_aspects_path %>

app/views/plan_aspects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Plan Aspects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plan_aspects.each do |plan_aspect| %>
      <tr>
        <td><%= plan_aspect.name %></td>
        <td><%= link_to 'Show', plan_aspect %></td>
        <td><%= link_to 'Edit', edit_plan_aspect_path(plan_aspect) %></td>
        <td><%= link_to 'Destroy', plan_aspect, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plan Aspect', new_plan_aspect_path %>

app/views/plan_aspects/new.html.erb
<h1>New Plan Aspect</h1>

<%= render 'form', plan_aspect: @plan_aspect %>

<%= link_to 'Back', plan_aspects_path %>

app/views/plan_aspects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @plan_aspect.name %>
</p>

<%= link_to 'Edit', edit_plan_aspect_path(@plan_aspect) %> |
<%= link_to 'Back', plan_aspects_path %>